// Mocks generated by Mockito 5.4.6 from annotations
// in kanban_flow/test/features/kanban/kanban_mocks.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'package:kanban_flow/src/common/enums/task_status_enum.dart' as _i4;
import 'package:kanban_flow/src/features/kanban/models/task_model.dart' as _i2;
import 'package:kanban_flow/src/features/kanban/repositories/kanban_repository.dart'
    as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeKanbanModel_0 extends _i1.SmartFake implements _i2.KanbanModel {
  _FakeKanbanModel_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [KanbanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockKanbanRepository extends _i1.Mock implements _i3.KanbanRepository {
  MockKanbanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.KanbanModel findAllTasks() =>
      (super.noSuchMethod(
            Invocation.method(#findAllTasks, []),
            returnValue: _FakeKanbanModel_0(
              this,
              Invocation.method(#findAllTasks, []),
            ),
          )
          as _i2.KanbanModel);

  @override
  void updateTaskStatus(String? taskId, _i4.TaskStatusEnum? newStatus) =>
      super.noSuchMethod(
        Invocation.method(#updateTaskStatus, [taskId, newStatus]),
        returnValueForMissingStub: null,
      );

  @override
  void addTask(String? title, _i4.TaskStatusEnum? initialStatus) =>
      super.noSuchMethod(
        Invocation.method(#addTask, [title, initialStatus]),
        returnValueForMissingStub: null,
      );
}
